export const SKILLS = [
	{
		icon: "Front",
		title: "Desarrollo & Herramientas de apoyo",
		tecnologies: [
			"Git",
			"GitHub",
			"VS Code",
			"Figma",
			"Scrum",
			"Jira",
			"CI/CD",
			"Jenkins",
		],
	},
	{
		icon: "Responsive",
		title: "Frontend & Frameworks",
		tecnologies: [
			"HTML5",
			"CSS3",
			"JavaScript",
			"TypeScript",
			"React",
			"Next.js",
			"Astro",
			"Ant Design",
			"React Router",
			"Storybook",
		],
	},
	{
		icon: "Tools",
		title: "Testing, APIs & Deploy",
		tecnologies: [
			"Vitest",
			"React Testing Library",
			"API REST",
			"Axios",
			"React Query",
			"Netlify",
			"Railway",
		],
	},
]
